# DB-related parameters
database:
  db_url: bolt://publicip:7687
  db_username: username
  db_password: password@dev
  top_k: 1
  neo4j_deeplink: "http://neodash.graphapp.io/xxxx"

# Slack-related parameters
slack:
  slack_bot_token: slack_bot_token
  slack_app_token: slack_app_token
  
# Model API parameters
openai_model_api:
  api_key: openai_model_api_key
  main_model: main_model_name
  main_model_temperature: 0
  support_model: support_model_name
  support_model_temperature: 0
  embedding_model: embedding_model_name

# LLM Chain Setups
llm_chain_setups:
  main_model: ['chain1', 'chain2']
  main_model_json: ['chain3']
  support_model: ['chain4', 'chain5', 'chain6']
  support_model_json: []

# File paths
files:
  log_path: ./data/virtual-havruta.log
  pr_table_path: ./data/pr_table.csv

# Reference Settings
references:
  primary_source_filter: ['filter1', 'filter2', 'filter3']
  num_primary_citations: 1
  num_secondary_citations: 1
