name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release:
    name: Release Library
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
    if: |
      (github.repository == 'sefaria/AppliedAI')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/commit-analyzer@9.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
